### ISSUE TITLE
How to compile in windows?

### ISSUE THREAD

**Issue by braindamagedjustnow** [nil0x42/duplicut#14]
How to compile in windows?

**Comment by nil0x42** [comment]
Hi ! I never tried to compile duplicut for windows.
Some low level linux API calls are made for optimization, and some parts of the code rely on executable format & kernel memory handling assumptions, which are specific to UNIX-like OS.

It would need code adjustments to make it work on windows, even more without sacrificing performance.

Porting duplicut to windows is really not in my priorities, sorry :/

Just for the record, duplicut should compile fine on Darwin, as i tested and adapted it years ago

**Comment by sergeevabc** [comment]
Could someone be so kind to create ```.exe``` for the rest of us, mere Windows users? We need dedup too.
