### ISSUE TITLE
Purge both duplicates

### ISSUE THREAD

**Issue by Plodstack** [nil0x42/duplicut#35]
First suggestion on github - but I would interested in a flag when a duplicate is found do NOT write this to the output file.

I think I could cat a number of wordlists that I've already tried together - dedupe, then generate a larger wordlist cat this my merged word list, dedupe again but this time with the flag set it would not write the dupes to the output file. Leaving me with a list of words not tried. Hope that makes sense..

**Comment by nil0x42** [comment]
@Plodstack , someone wrote a duplicut wrapper who allows you to dedupe multiple wordlists. So you can use this to prepare your wordlists from small to big, without having duplicates at all.

here is the tool: https://github.com/yanncam/multiduplicut

hope it helps
