### ISSUE TITLE
No output produced (0 byte) for 9.2 Gb tab separated text file

### ISSUE THREAD

**Issue by matthiasho** [nil0x42/duplicut#40]
xxx-Product-Name:~/duplicut$ ./duplicut wordhuge.txt -o clean-wordhuge.txt 2>&1 | tee /tmp/duplicut-debug.log
[DLOG1 26 13:16:34 optparse.c:236]: using wordhuge.txt as input file
[DLOG1 26 13:16:34   status.c:70 ]: CALL update_status(FCOPY_START)
[DLOG1 26 13:16:34   status.c:104]: CALL set_status(FILE_SIZE, 9944557870)
[DLOG1 26 13:16:40     file.c:217]: 
[DLOG1 26 13:16:40     file.c:218]: ---------- g_file ------------
[DLOG1 26 13:16:40     file.c:219]: g_file->fd:           4
[DLOG1 26 13:16:40     file.c:220]: g_file->name:         clean-wordhuge.txt
[DLOG1 26 13:16:40     file.c:221]: g_file->addr:         0x7f09fd9ea000
[DLOG1 26 13:16:40     file.c:222]: g_file->info.st_size: 9.3G (9944557870)
[DLOG1 26 13:16:40     file.c:224]: ------------------------------
[DLOG1 26 13:16:40   config.c:120]: 
[DLOG1 26 13:16:40   config.c:121]: --------- memstate -----------
[DLOG1 26 13:16:40   config.c:122]: memstate.page_size:      4096
[DLOG1 26 13:16:40   config.c:123]: memstate.mem_available:  80.5G (86460444672)
[DLOG1 26 13:16:40   config.c:125]: ------------------------------
[DLOG1 26 13:16:40   config.c:127]: 
[DLOG1 26 13:16:40   config.c:128]: ---------- g_conf ------------
[DLOG1 26 13:16:40   config.c:129]: g_conf.infile_name:       wordhuge.txt
[DLOG1 26 13:16:40   config.c:130]: g_conf.outfile_name:      clean-wordhuge.txt
[DLOG1 26 13:16:40   config.c:131]: g_conf.threads:           48
[DLOG1 26 13:16:40   config.c:132]: g_conf.line_max_size:     64
[DLOG1 26 13:16:40   config.c:133]: g_conf.hmap_size:         18.5G (2486139419 slots of 64bits)
[DLOG1 26 13:16:40   config.c:136]: g_conf.chunk_size:        9.3G (9944557870)
[DLOG1 26 13:16:40   config.c:138]: g_conf.filter_printable:  0
[DLOG1 26 13:16:40   config.c:139]: g_conf.memlimit:          9223372036854775807
[DLOG1 26 13:16:40   config.c:140]: ------------------------------
[DLOG1 26 13:16:40   config.c:141]: 
[DLOG1 26 13:16:40   status.c:112]: CALL set_status(CHUNK_SIZE, 9944557870)
[DLOG1 26 13:16:40   status.c:74 ]: CALL update_status(TAGDUP_START)
[DLOG1 26 13:16:46   status.c:86 ]: CALL update_status(CTASK_DONE)
[DLOG1 26 13:16:46   status.c:80 ]: CALL update_status(CHUNK_DONE)
[DLOG1 26 13:16:46   status.c:93 ]: CALL update_status(FCLEAN_START)

(On a 24 core, 192 Gb ram machine.  Ava mem  80 Gb)

**Comment by nil0x42** [comment]
Hi ! Sounds like a big issue..
Let me ask some questions:
* what is the average line size of your wordlist ? (no need to calculate exact average, just tell me some guess)
* does duplicut pass tests on your machine ? (`CC=gcc ARCH=x64 ./test/run.sh`)

**Comment by nil0x42** [comment]
If all your lines are over 64 bytes long, then having no output is expected (`--line-max-size` option)

**Comment by nil0x42** [comment]
No, the --line-max-size is an additional filter of max-size at which a line should be considered as valid.
Duplicut has been initially created with passwords deduping in mind, so a default value of 64 chars is nice.

But duplicut can handle lines of up-to 255 chars. Just set `--line-max-size 255` (or 150 if you prefer).

If it works after that, please let me know !
Have a nice day.

**Comment by matthiasho** [comment]
Thank for the advice.
I see that there is now a reduction in nos of lines...


Need some time to verify that removed lines are indeed duplicate.
Don't have a nice day, have a great day !

   On Friday, March 11, 2022, 09:31:34 PM GMT+8, nil0x42 ***@***.***> wrote:  
 
 


No, the --line-max-size is an additional filter of max-size at which a line should be considered as valid.
Duplicut has been initially created with passwords deduping in mind, so a default value of 64 chars is nice.

But duplicut can handle lines of up-to 255 chars. Just set --line-max-size 255 (or 150 if you prefer).

If it works after that, please let me know !
Have a nice day.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
