### ISSUE TITLE
how does it work on windows?

### ISSUE THREAD

**Issue by concacdkmvl** [nil0x42/duplicut#51]
do you have any build for windows? exe file?

**Comment by nil0x42** [comment]
No, indeed i've optimized syscalls for linux. And implemented (theorically) support for darwin. But no suport for windows yet

**Comment by Vizonex** [comment]
@nil0x42 sorry for the ping but I have good news, I managed to pull off a [windows fork](https://github.com/Vizonex/wincut) and when the branch starts to mature I'll merge my version to yours with the use of macros.
